<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <UsedAvaloniaProducts></UsedAvaloniaProducts>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ZTE IMEI Studio">
      <HintPath>../src/bin/Debug/net10.0/osx-arm64/ZTE IMEI Studio.dll</HintPath>
    </Reference>
    <PackageReference Include="Avalonia.Headless" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.12" />
  </ItemGroup>
</Project>
