"""Build the exact-profile launcher extension and its pinned installer."""
from pathlib import Path
import argparse, hashlib, subprocess, os, shutil
from abi import header, verify
ROOT = Path(__file__).resolve().parents[2]
SRC = Path(__file__).resolve().parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--output', type=Path, help='Stage a bundle without changing resources or vpnctl pins')
parser.add_argument('--verify-only', action='store_true')
args = parser.parse_args()
OUT = args.output or ROOT / 'MacIMEI/Resources/VPN'
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
assert (SRC/'abi.h').read_text() == header(), 'Regenerate abi.h with abi.py'
references = [os.environ[k] for k in ('ZTE_STOCK_UI','ZTE_RUSSIAN_UI','ZTE_B28_STOCK_UI','ZTE_B28_RUSSIAN_UI') if os.environ.get(k)]
for reference in references:
    print('Verified exact UI ABI:', verify(Path(reference).read_bytes()))
if not references: print('Reference ELF audit skipped; runtime exact UI SHA guards remain mandatory')
if args.verify_only:
    if not references: raise SystemExit('No reference ELFs supplied')
    raise SystemExit(0)
OUT.mkdir(parents=True, exist_ok=True)
subprocess.run([os.environ.get('ZTE_CROSS_CC') or shutil.which('aarch64-linux-musl-gcc'),'-s',f'-ffile-prefix-map={ROOT}=.',f'-ffile-prefix-map={Path.home()}=/build','-shared','-fPIC','-O2','-Wall','-Wextra','-Werror','-Wno-misleading-indentation','-fvisibility=hidden','-pthread','-Wl,-z,relro,-z,now','-o',str(OUT/'launcher.so'),str(SRC/'launcher.c'),str(SRC/'backend.c'),str(SRC/'vpn-process.c'),str(SRC/'vpn-model.c'),str(SRC/'esim-model.c'),str(SRC/'esim-backend.c'),str(SRC/'esim-process.c'),str(SRC/'page-layout.c'),str(SRC/'telemetry.c'),str(SRC/'info-layout.c')],check=True)
names = ['launcher.so','launcher-run.sh','launcher-watch.sh','launcher-service.sh','launcher-start.sh']
for name in names[1:]:
    source=SRC/'scripts'/name
    subprocess.run(['sh','-n',str(source)],check=True)
    (OUT/name).write_bytes(source.read_bytes())
(OUT/'launcher.sha256').write_text(''.join(f'{sha(OUT/name)}  {name}\n' for name in names))
names.append('launcher.sha256')
source=(SRC/'scripts/install-launcher.sh').read_text()
pins='\n'.join(f'[ "$(sha256sum "$stage/{name}" | cut -d\' \' -f1)" = {sha(OUT/name)} ] || exit 70' for name in names)
source=source.replace('# Generated by build.py.',pins)
(OUT/'install-launcher.sh').write_text(source)
subprocess.run(['sh','-n',str(OUT/'install-launcher.sh')],check=True)
if args.output is None:
    (ROOT/'ModemAgent/vpnctl/src/launcher.sha256').write_text(sha(OUT/'launcher.so'))
print('LAUNCHER',sha(OUT/'launcher.so'))
