namespace ZteImeiStudio.Windows;

internal sealed record OperationHelpSection(string Title, string Body, string? Commands = null);
internal sealed record OperationHelpTopic(string Title, string AccessibleName, string Introduction,
    IReadOnlyList<OperationHelpSection> Sections);

/// <summary>
/// User-facing account of the implemented Windows workflows. Keep this aligned
/// with Core/OnboardingEngine.cs, Core/ImeiEngine*.cs and the pinned device payloads.
/// </summary>
internal static class OperationHelpContent
{
    public static OperationHelpTopic Preparation { get; } = new(
        "Как выполняется предварительная подготовка",
        "Подробно о предварительной подготовке модема",
        "Кнопка подготавливает доступ к модему через штатный Web, USB ADB и затем SSH. Она может восстановить изменённый бэкап настроек, чтобы включить ADB на проверенной B31, и установить агент с отдельным SSH-доступом. Открытие этой справки ничего не запускает.",
        [
            new("1. Условия запуска и блокировки",
                "Для подготовки нужны IPv4-адрес модема, пароль штатного Web, пароль агента и Backup-key suffix для вашей прошивки. Если SSH уже подключён в этой сессии, повторная предварительная подготовка не запускается. Приложение берёт локальную блокировку operation.lock и останавливается при незавершённой смене IMEI или восстановлении полного образа. «Проверить подключения» и «Подключиться» — отдельные действия: они не запускают установщик. Для новой установки нужен USB-кабель с передачей данных. Пароли не записываются в локальный журнал подготовки.",
                "%LOCALAPPDATA%\\ZTE IMEI Studio\\operation.lock\n%LOCALAPPDATA%\\ZTE IMEI Studio\\setup-pending.json"),
            new("2. Вход в Web и свежий архив настроек",
                "Windows-приложение запрашивает challenge zte_web_sault и отправляет штатному web_login хэш пароля с challenge. Затем читает IMEI и версии прошивки, вызывает создание нового зашифрованного бэкапа Web-настроек и скачивает его. После загрузки повторно проверяется Web-идентичность. Архив и сведения о нём сохраняются в отдельном каталоге SetupBackups/<UUID>, даже когда SSH уже был настроен. Это бэкап настроек, а не полный образ разделов модема.",
                "POST http://<IPv4>/ubus/ → zwrt_web.web_login_info / web_login\nPOST http://<IPv4>/ubus/ → zwrt_web.device_info\nPOST http://<IPv4>/ubus/ → device_backup_proc {\"procType\":\"web\"}\nGET  http://<IPv4>/backup/back_parameter\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SetupBackups\\<UUID>\\back_parameter.original\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SetupBackups\\<UUID>\\identity.json\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SetupBackups\\<UUID>\\manifest.json"),
            new("3. Проверка архива и подготовка ADB на B31",
                "Архив расшифровывается в памяти ключом из IMEI и введённого владельцем Backup-key suffix. Суффикс не включён в публичную сборку, не сохраняется в настройках или журнале и очищается из формы после операции. Проверяются OpenSSL Salted__, вложенные gzip/tar, MD5 внутреннего архива, имена файлов и метаданные. Если ADB ещё не доступен, внутри etc/rc.local после #!/bin/sh добавляется только строка включения USB ADB; остальные записи сверяются с исходными. После повторной упаковки и шифрования результат вновь расшифровывается для проверки. Изменённая копия сохраняется как back_parameter.adb-only только перед её загрузкой. Если уже найден проверенный SSH с агентом либо подходящий root USB ADB, восстановление бэкапа не отправляется.",
                "# Единственная добавляемая строка внутри etc/rc.local:\necho 1 > /sys/class/android_usb/android0/usb_op\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SetupBackups\\<UUID>\\back_parameter.adb-only"),
            new("4. Однократное восстановление для включения ADB",
                "На B31 приложение сверяет Web-устройство перед загрузкой изменённого архива и перед восстановлением. Штатный CGI должен вернуть SHA-256 точно загруженных байт. До вызова device_restore_proc в setup-pending.json сохраняется отметка restore-requested. Восстановление перезагружает модем. При обрыве HTTP запрос не повторяется вслепую: приложение до четырёх минут ожидает подтверждённый USB ADB. Для экспериментальной B02 этот путь включения ADB через Web не используется; root USB ADB должен уже работать.",
                "POST http://<IPv4>/cgi-bin/cgi-upload → /tmp/back_parameter\nPOST http://<IPv4>/ubus/ → device_restore_proc {\"procType\":\"web\"}"),
            new("5. Выбор USB-устройства и проверка профиля",
                "Встроенный adb.exe перечисляет USB-устройства. Для каждого кандидата проверяются root, aarch64, SHA-256 modem.b16 и diag-router, eMMC CID, boot_id и данные штатного Web. IMEI и версии должны совпасть с загруженным Web-бэкапом. При нескольких совпадениях установка останавливается. По умолчанию допускается проверенная MU5250 B31. Галочка пропуска общей проверки разрешает только известный экспериментальный профиль B02 с уже доступным root USB ADB; установщик всё равно требует точных известных хэшей. На B02 подготовка доступа не разрешает запись IMEI — доступно лишь чтение.",
                "adb.exe devices -l\nadb.exe -s <serial> shell 'id -u; uname -m'\nsha256sum /firmware/image/modem.b16 /usr/bin/diag-router\ncat /sys/block/mmcblk0/device/cid /proc/sys/kernel/random/boot_id\nubus call zwrt_web device_info '{}'"),
            new("6. Передача и установка компонентов",
                "Перед установкой проверяются SHA-256 встроенных zte-agent, dropbear и сценариев, CID, свободное место, типы и права каталогов. При необходимости создаются /data/local и /data/local/tmp. В приватный /data/local/tmp/zte-imei-setup-<UUID> через adb push передаются агент, Dropbear, установщик, сценарий автозапуска, открытый SSH-ключ и сценарий запуска агента. Каждый incoming-файл сверяется по SHA-256 до переименования. До постоянных правок установщик сохраняет исходные файлы и их хэши в приватном журнале /data/local/tmp/zte-imei-installations/<UUID>.",
                "adb.exe -s <serial> push <файл> <stage>/incoming-<UUID>\nsha256sum <stage>/incoming-<UUID>\nsh <stage>/setup-agent.sh <stage> <CID> <SHA256-компонентов> <профиль>"),
            new("7. Какие файлы меняются на модеме",
                "Если агента ещё нет, он размещается в /data/zte-agent, а root-сценарий запуска с паролем агента — в /data/local/tmp/start_zte_agent.sh. Уже существующий агент и его пароль сохраняются. При необходимости Dropbear и dropbearkey размещаются в /data/bin; открытый ключ приложения добавляется в /etc/dropbear/authorized_keys без удаления других ключей. Серверные ключи хранятся в /etc/dropbear, их копии и authorized_keys — в /data/dropbear. В /etc/rc.local добавляется вызов /data/local/tmp/start_zte_imei_studio.sh: он запускает отсутствующий агент и отдельный SSH-слушатель на порту 2222 с входом по ключу. До правок установщик сохраняет прежние версии затронутых файлов в своём журнале.",
                "# Добавляемый автозапуск в /etc/rc.local:\nsh /data/local/tmp/start_zte_imei_studio.sh\n# Отдельный SSH-слушатель:\n/data/bin/dropbear -s -P /var/run/zte-imei-dropbear.pid -p 2222"),
            new("8. SSH-ключ и итоговая проверка",
                "Встроенный ssh-keygen.exe создаёт или повторно использует локальную пару Ed25519. Приватный ключ остаётся в %LOCALAPPDATA% с ограниченными Windows ACL; на модем передаётся только публичный. Серверный Ed25519 host key читается через проверенный ADB с повторной сверкой устройства и закрепляется в отдельном known_hosts. SSH-соединение устанавливает библиотека SSH.NET; ключ сервера сравнивается с закреплённым побайтно, без автоматического принятия нового ключа. После установки сверяются идентичности ADB и SSH, процесс агента и, для нового агента, вход заданным паролем. На B31 дополнительно читается пара NV и сравнивается с API; на B02 запись NV не выполняется. Только после проверок установщик получает --commit.",
                "# Локальные файлы Windows:\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SSH\\id_ed25519\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SSH\\id_ed25519.pub\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SSH\\known_hosts\n# Host key читается через ADB:\n/data/bin/dropbearkey -y -f /etc/dropbear/dropbear_ed25519_host_key\nsh <stage>/setup-agent.sh --commit <журнал> <CID> <профиль>"),
            new("9. Если связь прервалась",
                "Локальный setup-pending.json хранит стадию и идентичность. Уже отправленное восстановление Web-бэкапа автоматически не повторяется. Если вызов установщика мог дойти до устройства, приложение сверяет удалённый журнал; автоматическое завершение возможно только из подтверждённых состояний ready или complete. Оригинальный архив сохраняется в SetupBackups/<UUID>; installation.log появляется после ответа установщика, setup-result.json — после успешного завершения. Временный локальный файл с паролем удаляется после передачи. Подготовка сама по себе не записывает новые IMEI, не устанавливает Launcher или русификацию и не прошивает raw-раздел ZTEDATA.",
                "%LOCALAPPDATA%\\ZTE IMEI Studio\\setup-pending.json\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SetupBackups\\<UUID>\\installation.log\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SetupBackups\\<UUID>\\setup-result.json")
        ]);

    public static OperationHelpTopic Imei { get; } = new(
        "Как записываются оба IMEI",
        "Подробно о записи обоих IMEI",
        "Кнопка меняет два индекса NV550 через проверенные помощники DIAG/EFS. До первой записи приложение сохраняет исходные NV и EFS config на Windows, временно разрешает запись и после двух перезагрузок подтверждает итог. Это операция только для проверенной MU5250 B31; экспериментальная B02 остаётся режимом чтения IMEI.",
        [
            new("1. Доступ и ограничения",
                "Запись запускается только после подключения root SSH; эта кнопка сама не выполняет предварительную подготовку. SSH.NET использует локальный Ed25519 private key и точный host key из known_hosts, полученный при подготовке. Оба новых IMEI должны состоять из 15 цифр, иметь правильную контрольную цифру и различаться. Перед записью снова требуются точные SHA-256 прошивки MU5250 B31 и diag-router: галочка пропуска общей проверки не снимает этот запрет. Незавершённая подготовка или операция IMEI блокирует новую запись.",
                "%LOCALAPPDATA%\\ZTE IMEI Studio\\SSH\\id_ed25519\n%LOCALAPPDATA%\\ZTE IMEI Studio\\SSH\\known_hosts\nsha256sum /firmware/image/modem.b16 /usr/bin/diag-router"),
            new("2. Исходные данные и блокировки",
                "Приложение сверяет eMMC CID, хэши прошивки и boot_id. Оно берёт локальную imei-operation.lock, сохраняет токен в imei-lock.json и создаёт принадлежащую операции /tmp/zte-imei-app.lock на модеме. Помощник zte_nv читает оба 128-байтных индекса NV550; значения IMEI сравниваются с get_imei и get_imei2 штатного ubus API. Если предложенная пара уже записана, операция не начинается.",
                "cat /sys/block/mmcblk0/device/cid /proc/sys/kernel/random/boot_id\n<zte_nv> --snapshot\nubus call zwrt_zte_mdm.api get_imei\nubus call zwrt_zte_mdm.api get_imei2\n%LOCALAPPDATA%\\ZTE IMEI Studio\\imei-lock.json\n/tmp/zte-imei-app.lock"),
            new("3. Проверенные временные помощники",
                "Перед каждым вызовом встроенные zte_nv, zte_config и zte_config_read сверяются с Resources/Helpers/helpers.json. В приватный /tmp/zte-imei-<UUID> помощник передаётся по stdin SSH, получает права 700 и снова проверяется по SHA-256. Если нужен план, он передаётся отдельно и проверяется таким же образом. После вызова приложение пытается удалить только свой временный каталог. Эти помощники используют DIAG/EFS и не получают произвольные команды записи.",
                "mkdir /tmp/zte-imei-<UUID>\ncat > <tmp>/helper; chmod 700 <tmp>/helper; sha256sum <tmp>/helper\ncat > <tmp>/plan; sha256sum <tmp>/plan\n<tmp>/helper <проверенный-режим> <tmp>/plan"),
            new("4. Бэкап до первой записи",
                "zte_config_read читает /config внутри EFS модемного процессора — это не Linux-файл /config. Проверяется структура B31: 15 073 байта, 249 записей, CRC и исходное значение флага записи. Оба NV перечитываются, чтобы исключить изменение во время бэкапа. В Backups/IMEI/<UUID> сохраняются nv0.bin, nv1.bin, config.bin и manifest.json с SHA-256, IMEI и идентичностью устройства; приложение сразу открывает копию и проверяет её. Лишь затем создаётся imei-pending.json с целевыми полными NV. В каждом 128-байтном NV меняются только первые 9 байт кодировки IMEI; остальные 119 байт сохраняются. Этот бэкап не является полным образом модема.",
                "<zte_config_read> --read-config\n<zte_nv> --snapshot\n%LOCALAPPDATA%\\ZTE IMEI Studio\\Backups\\IMEI\\<UUID>\\nv0.bin\n%LOCALAPPDATA%\\ZTE IMEI Studio\\Backups\\IMEI\\<UUID>\\nv1.bin\n%LOCALAPPDATA%\\ZTE IMEI Studio\\Backups\\IMEI\\<UUID>\\config.bin\n%LOCALAPPDATA%\\ZTE IMEI Studio\\Backups\\IMEI\\<UUID>\\manifest.json\n%LOCALAPPDATA%\\ZTE IMEI Studio\\imei-pending.json"),
            new("5. Временный флаг и первая перезагрузка",
                "Из исходного config формируется кандидат: байт флага config102 по смещению 499 меняется с 0 на 1, CRC пересчитывается; прочие байты сохраняются. zte_config получает план «исходный + кандидат», включает разрешение записи через проверенные операции EFS и затем приложение повторно читает config. Стадия и время сохраняются до потенциально неоднозначного вызова. Штатная команда перезагрузки отправляется один раз; затем до четырёх минут ожидаются тот же модем и новый boot_id. Потеря SSH во время перезагрузки сама по себе не означает неудачу.",
                "<zte_config> --enable-flag <план-original+candidate>\nubus call zwrt_mc.device.manager device_reboot '{\"moduleName\":\"web\"}'"),
            new("6. Два индекса NV550 последовательно",
                "После загрузки проверяются config и оба NV: каждый должен совпадать с известным исходным либо целевым содержимым. Создаётся 512-байтный план из текущих NV0/NV1 и целевых NV0/NV1. Помощник zte_nv --apply-plan последовательно записывает индексы 0 и 1, сверяя данные после каждого шага; затем приложение отдельно перечитывает пару NV и оба значения ubus. Это не атомарная запись двух слотов. При сбое помощник может попытаться восстановить известные исходные записи, но при потере питания или связи результат требует проверки.",
                "<zte_nv> --apply-plan <план-512-байт>\n<zte_nv> --snapshot\nubus call zwrt_zte_mdm.api get_imei\nubus call zwrt_zte_mdm.api get_imei2"),
            new("7. Возврат config и заключительная проверка",
                "После подтверждения пары zte_config возвращает точный исходный EFS config, включая прежний флаг и CRC. Приложение сохраняет стадию final-reboot, один раз запрашивает вторую перезагрузку и ждёт нового boot_id того же модема. После неё проверяются NV, API и побайтное совпадение config с исходным. Только при полном успехе создаётся IMEIResults/<UUID>.json и удаляется imei-pending.json. В обычной новой операции ожидаются две перезагрузки; при продолжении уже выполненные шаги определяются по журналу и фактическому состоянию.",
                "<zte_config> --restore-original-config <план-original+candidate>\nubus call zwrt_mc.device.manager device_reboot '{\"moduleName\":\"web\"}'\n<zte_config> --check-original <план-original+candidate>\n%LOCALAPPDATA%\\ZTE IMEI Studio\\IMEIResults\\<UUID>.json"),
            new("8. Продолжение и восстановление пары",
                "Если операция прервалась, бэкап и imei-pending.json остаются. Кнопка «Продолжить незавершённую операцию» заново проверяет устройство, хэши бэкапа, текущие NV и config; неизвестное состояние останавливает автоматическую запись. После неопределённого вызова config приложение требует паузу не менее 210 секунд, после записи NV — 150 секунд, прежде чем разрешить повторную сверку. «Восстановить» в списке бэкапов использует тот же защищённый процесс и сперва сохраняет свежую копию текущего состояния; посторонние 119 байт обоих NV должны совпасть с выбранной копией. Операция не прошивает raw-разделы и не заменяет полный образ ZTEDATA.",
                "%LOCALAPPDATA%\\ZTE IMEI Studio\\imei-pending.json\n%LOCALAPPDATA%\\ZTE IMEI Studio\\Backups\\IMEI\\<UUID>\\manifest.json")
        ]);
}
