<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ZTE U60Pro Manager</AssemblyName>
    <Product>ZTE U60Pro Manager</Product>
    <ApplicationIcon Condition="Exists('../Resources/Branding/AppIcon.ico')">../Resources/Branding/AppIcon.ico</ApplicationIcon>
    <RootNamespace>ZteImeiStudio.Windows</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
    <SatelliteResourceLanguages>ru;en</SatelliteResourceLanguages>
    <Version>1.24.3</Version>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <UsedAvaloniaProducts></UsedAvaloniaProducts>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.12" />
    <PackageReference Include="SSH.NET" Version="2025.0.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../Resources/Localization/en.json" LogicalName="ZteManager.Localization.en.json" />
    <Content Include="../Resources/**/*">
      <Link>Resources/%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>
