#!/usr/bin/env python3
"""Host-only tests for the persistent screen-localization installer.

The production shell is copied with device paths redirected into a temporary
filesystem. System commands are mocked; no SSH, ADB, real mount, or modem is used.
"""
from pathlib import Path
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import unittest


REPO = Path(__file__).resolve().parents[2]
RES = REPO / "MacIMEI/Resources/ScreenLocalization"
CID = "0123456789abcdef0123456789abcdef"
TOKEN = "11111111-2222-3333-4444-555555555555"
FIRMWARE = "604e22f213e1bef241296e5aae161991989fd8df790057935c07d45101ae4263"
STOCK = {
    "English.ini": REPO / "evidence/russian-ui-20260922/usr/ui/language/English.ini",
    "Chinese.ini": REPO / "evidence/russian-ui-chinese-slot-20260922/Chinese.original.ini",
    "zte_topsw_devui": REPO / "evidence/russian-ui-trial-20260922/zte_topsw_devui",
}
PAYLOAD = {
    "English.ini": RES / "English.ini",
    "Chinese.ini": RES / "Chinese.ini",
    "zte_topsw_devui": REPO / "evidence/russian-ui-font-trial-20260922/zte_topsw_devui",
}
TARGETS = {
    "English.ini": "/usr/ui/language/English.ini",
    "Chinese.ini": "/usr/ui/language/Chinese.ini",
    "zte_topsw_devui": "/usr/bin/zte_topsw_devui",
}


def sha(data):
    return hashlib.sha256(data).hexdigest()


MOCK_COMMANDS = r'''
from pathlib import Path
import hashlib,json,os,signal,stat,sys
r=Path(os.environ['MOCK_ROOT'])
name=sys.argv[1];args=sys.argv[2:]
def event(message):
 with (r/'calls').open('a') as f: f.write(message+'\n')
def digest(path):
 p=Path(path)
 if str(p).endswith('/firmware/image/modem.b16'):
  return os.environ['MOCK_FIRMWARE_SHA']
 raw=p.read_bytes()
 # Undo only the harness's device-path relocation for script integrity pins.
 # This also covers the init script generated by the real installer.
 if raw.startswith(b'#!/bin/sh') or '/etc/init.d/' in str(p) or p.name in ('install.sh','manager.sh','service.sh'):
  raw=raw.replace(str(r).encode(),b'')
 value=hashlib.sha256(raw).hexdigest()
 return json.loads((r/'digest-aliases.json').read_text()).get(value,value)
def failpoint(action):
 return os.environ.get('MOCK_FAIL')==action
if name=='id': print(0)
elif name=='uname': print('aarch64')
elif name=='sleep': pass
elif name=='sync':
 event('sync')
 base=r/'data/zte-imei-screen-ru'
 snapshot={'enabled':(base/'.enabled').exists(),'transaction':(base/'.transaction').exists(),'language':json.loads((r/'uci.json').read_text())['language']}
 with (r/'sync-trace.jsonl').open('a') as f: f.write(json.dumps(snapshot)+'\n')
 crash=os.environ.get('MOCK_CRASH')
 if snapshot['language']=='cn' and (
  (crash=='cn-without-enabled' and not snapshot['enabled']) or
  (crash=='enabled-with-transaction' and snapshot['enabled'] and snapshot['transaction'])):
  os.kill(os.getppid(),signal.SIGKILL)
elif name=='df': print('Filesystem 1024-blocks Used Available Capacity Mounted\nfixture 2000000 0 2000000 0 /')
elif name=='logger': event('logger '+' '.join(args))
elif name=='pidof':
 if not (r/'ui-running').exists(): sys.exit(1)
 print('424242')
elif name=='readlink':
 if args[-1].endswith('/proc/424242/exe'):
  print(str(r/'usr/bin/zte_topsw_devui'))
 else:
  try: print(os.readlink(args[-1]))
  except OSError: sys.exit(1)
elif name=='stat':
 fmt=args[args.index('-c')+1];p=Path(args[-1]);s=p.stat()
 values={'%u':'0','%g':'0','%a':oct(stat.S_IMODE(s.st_mode))[2:],'%h':str(s.st_nlink),'%s':str(s.st_size),'%F':'regular file' if p.is_file() else 'directory'}
 for key,value in values.items(): fmt=fmt.replace(key,value)
 print(fmt)
elif name=='sha256sum':
 if args[0]=='-c':
  for line in Path(args[-1]).read_text().splitlines():
   expected,path=line.split(None,1);path=path.lstrip('*')
   if digest(path)!=expected: sys.exit(1)
 else:
  for path in args: print(digest(path)+'  '+path)
elif name=='uci':
 args=[x for x in args if x!='-q']
 state=json.loads((r/'uci.json').read_text());action=args[0]
 if action=='get':
  if args[1]!='zwrt_deviceui.Device.device_language': sys.exit(1)
  print(state['language'])
 elif action=='changes': print(state['pending'],end='')
 elif action=='set':
  event('uci-set '+args[1])
  if failpoint('uci-set'): sys.exit(1)
  key,value=args[1].split('=',1)
  if key!='zwrt_deviceui.Device.device_language': sys.exit(2)
  state['language']=value
  state['pending'] += key+'='+value+'\n'
  (r/'uci.json').write_text(json.dumps(state))
 elif action=='commit':
  event('uci-commit '+args[1])
  if failpoint('uci-commit'): sys.exit(1)
  state['pending']='';(r/'uci.json').write_text(json.dumps(state))
 else: raise RuntimeError('Unsupported UCI command: '+repr(args))
elif name=='service-fixture':
 action=args[0];event('service-'+action)
 if failpoint('service-'+action): sys.exit(1)
 if action=='stop': (r/'ui-running').unlink(missing_ok=True)
 elif action=='start':
  if os.environ.get('MOCK_FAIL_CANDIDATE_START')=='1':
   if (r/'usr/bin/zte_topsw_devui').read_bytes() != (r/'stock/zte_topsw_devui').read_bytes(): sys.exit(1)
  if os.environ.get('MOCK_REQUIRE_STOCK_START')=='1':
   if (r/'usr/bin/zte_topsw_devui').read_bytes() != (r/'stock/zte_topsw_devui').read_bytes(): sys.exit(1)
  (r/'ui-running').touch()
 else: raise RuntimeError('Unsupported service action: '+action)
elif name=='mount':
 if args[:2]!=['-o','bind']: raise RuntimeError('Unexpected mount: '+repr(args))
 source,target=map(Path,args[2:]);event('mount-'+target.name)
 if failpoint('mount-'+target.name): sys.exit(1)
 if (r/'ui-running').exists(): raise RuntimeError('UI must stop before mounting')
 records=json.loads((r/'mounts.json').read_text())
 n=len(records);backup=r/f'mount-backup-{n}'
 backup.write_bytes(target.read_bytes());target.write_bytes(source.read_bytes())
 relative=source.relative_to(r/'data')
 records.append({'source':str(source),'target':str(target),'backup':str(backup),'root':'/'+str(relative),'dev':'179:17'})
 (r/'mounts.json').write_text(json.dumps(records))
 with (r/'proc/self/mountinfo').open('a') as f:
  f.write(f'{100+n} 1 179:17 /{relative} {target} rw - ext4 /dev/userdata rw\n')
elif name=='umount':
 target=Path(args[-1]);event('umount-'+target.name)
 if failpoint('umount-'+target.name): sys.exit(1)
 if (r/'ui-running').exists(): raise RuntimeError('UI must stop before unmounting')
 records=json.loads((r/'mounts.json').read_text())
 hits=[x for x in records if x['target']==str(target)]
 if len(hits)!=1: raise RuntimeError('Unmount of absent/stacked fixture mount')
 record=hits[0];target.write_bytes(Path(record['backup']).read_bytes())
 if target.name=='zte_topsw_devui' and os.environ.get('MOCK_CORRUPT_AFTER_UI_UNMOUNT')=='1':
  target.write_bytes(b'unknown changed original ELF')
 records.remove(record);(r/'mounts.json').write_text(json.dumps(records))
 path=r/'proc/self/mountinfo'
 path.write_text(''.join(x+'\n' for x in path.read_text().splitlines() if x.split()[4]!=str(target)))
else: raise RuntimeError('Unsupported mock: '+name)
'''


class ScreenLocalizationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="zte-screen-localization-", dir="/private/tmp")
        self.root = Path(self.temp.name)
        self.stage = self.root / f"tmp/zte-screen-ru-install-{TOKEN}"
        self.installed = self.root / "data/zte-imei-screen-ru"
        self.bin = self.root / "mock-bin"
        self.bin.mkdir()
        self.stage.mkdir(parents=True)
        self.stage.chmod(0o700)
        (self.root/"data").mkdir()
        self.env = dict(os.environ, MOCK_ROOT=str(self.root), MOCK_FIRMWARE_SHA=FIRMWARE,
                        PATH=str(self.bin)+":/usr/bin:/bin")
        self.write("/calls", "")
        self.write("/digest-aliases.json", "{}")
        self.write("/mounts.json", "[]")
        self.write("/uci.json", json.dumps({"language":"en", "pending":"", "unrelated":"preserve"}))
        self.write("/cache/language.txt", "english", 0o640)
        self.write("/sys/block/mmcblk0/device/cid", CID+"\n")
        self.write("/proc/uptime", "1000.00 0.00\n")
        self.write("/proc/sys/kernel/random/boot_id", "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\n")
        self.write("/firmware/image/modem.b16", "firmware fixture")
        self.write("/etc/rc.local", "#!/bin/sh\n# unrelated customization\necho preserved\nexit 0\n", 0o751)
        (self.root/"etc/rc.d").mkdir()
        (self.root/"stock").mkdir()
        self.write("/ui-running", "")
        self.write("/proc/self/mountinfo", (
            "1 0 179:0 / / ro - ext4 /dev/root ro\n"
            f"2 1 179:17 / {self.root}/data rw - ext4 /dev/userdata rw\n"
            f"3 1 0:10 / {self.root}/tmp rw - tmpfs tmpfs rw\n"
            f"4 1 0:11 / {self.root}/etc rw - overlay overlay rw\n"))
        self.write("/proc/mounts", (
            "/dev/root / ext4 ro 0 0\n"
            f"/dev/userdata {self.root}/data ext4 rw 0 0\n"
            f"tmpfs {self.root}/tmp tmpfs rw 0 0\n"
            f"overlay {self.root}/etc overlay rw 0 0\n"))
        (self.root/"tmp").mkdir(exist_ok=True)
        dispatcher=self.root/"dispatch.py"
        dispatcher.write_text(MOCK_COMMANDS)
        for name in ["id","uname","sleep","sync","df","logger","pidof","readlink","stat","sha256sum","uci","mount","umount"]:
            self.command(name, "#!/bin/sh\nexec "+shlex.quote(sys.executable)+" "+shlex.quote(str(dispatcher))+" "+name+' "$@"\n')
        stock_init=(REPO/"evidence/russian-ui-persistent-20260922/stock-ui-init.sh").read_text()
        self.write("/etc/init.d/zte_topsw_devui",self.redirect(stock_init),0o755)
        fixture_service=shlex.quote(sys.executable)+" "+shlex.quote(str(dispatcher))+" service-fixture"
        rc_common='\n'.join([
            '#!/bin/sh', 'script=$1', 'action=$2', '. "$script"',
            'procd_open_instance() { :; }', 'procd_set_param() { :; }',
            'procd_close_instance() { '+fixture_service+' start; }',
            'case "$action" in',
            ' start) if command -v start_service >/dev/null; then start_service; else start; fi;;',
            ' boot) boot;;', ' stop) '+fixture_service+' stop;;',
            ' *) exit 2;;', 'esac', ''])
        self.write("/etc/rc.common",rc_common,0o755)
        for name, original in STOCK.items():
            self.write(TARGETS[name], original.read_bytes(), 0o755 if name=="zte_topsw_devui" else 0o644)
            shutil.copyfile(original,self.root/"stock"/name)
        for name, source in PAYLOAD.items():
            shutil.copyfile(source,self.stage/name)
            (self.stage/name).chmod(0o755 if name=="zte_topsw_devui" else 0o644)
        self.original_rc=(self.root/"etc/rc.local").read_bytes()

    def tearDown(self):
        self.temp.cleanup()

    def write(self,path,data,mode=0o600):
        p=self.root/path.lstrip("/")
        p.parent.mkdir(parents=True,exist_ok=True)
        p.write_bytes(data.encode() if isinstance(data,str) else data)
        p.chmod(mode)
        return p

    def command(self,name,text):
        p=self.bin/name;p.write_text(text);p.chmod(0o700)

    def redirect(self,text):
        pattern=r"(?<![A-Za-z0-9_])/(?:data|etc|tmp|sys|cache|firmware|proc|usr)(?=/|[\s\"';)]|$)"
        return re.sub(pattern,lambda m:str(self.root)+m.group(),text)

    def prepare_scripts(self):
        aliases={}
        for name in ["install.sh","service.sh"]:
            raw=(RES/name).read_bytes()
            rewritten=self.redirect(raw.decode()).encode()
            (self.stage/name).write_bytes(rewritten)
            (self.stage/name).chmod(0o700)
            aliases[sha(rewritten)]=sha(raw)
        (self.root/"digest-aliases.json").write_text(json.dumps(aliases))

    def run_script(self,script,*args,**env):
        return subprocess.run(["/bin/sh",str(script),*map(str,args)],env=dict(self.env,**env),
                              capture_output=True,text=True,timeout=45)

    def install(self,**env):
        self.prepare_scripts()
        return self.run_script(self.stage/"install.sh","install",self.stage,CID,**env)

    def manager(self,mode,**env):
        return self.run_script(self.installed/"manager.sh",mode,CID,**env)

    def boot(self,**env):
        return self.run_script(self.installed/"manager.sh","boot",**env)

    def boot_service(self,**env):
        wrapper=self.root/"boot-service-fixture.sh"
        wrapper.write_text(". "+shlex.quote(str(self.root/"etc/init.d/zte_imei_screen_ru"))+"\nboot\n")
        return self.run_script(wrapper,**env)

    def start_stock_ui(self,**env):
        return self.run_script(self.root/"etc/rc.common",self.root/"etc/init.d/zte_topsw_devui","start",**env)

    def cold_boot_state(self):
        """Model reboot losing bind mounts/processes but retaining /data and UCI."""
        records=json.loads((self.root/"mounts.json").read_text())
        for record in reversed(records):
            Path(record["target"]).write_bytes(Path(record["backup"]).read_bytes())
        p=self.root/"proc/self/mountinfo"
        targets={x["target"] for x in records}
        p.write_text("".join(x+"\n" for x in p.read_text().splitlines() if x.split()[4] not in targets))
        (self.root/"mounts.json").write_text("[]")
        (self.root/"ui-running").unlink(missing_ok=True)
        (self.root/"calls").write_text("")
        self.write("/proc/uptime","10.00 0.00\n")
        self.write("/proc/sys/kernel/random/boot_id","bbbbbbbb-bbbb-cccc-dddd-eeeeeeeeeeee\n")
        for child in (self.root/"tmp").iterdir():
            if child.is_dir(): shutil.rmtree(child)
            else: child.unlink()

    def calls(self):
        return (self.root/"calls").read_text().splitlines()

    def assert_success(self,result):
        self.assertEqual(result.returncode,0,result.stdout+result.stderr)

    def assert_originals(self):
        for name,target in TARGETS.items():
            self.assertEqual((self.root/target.lstrip("/")).read_bytes(),STOCK[name].read_bytes(),name)

    def language(self):
        return json.loads((self.root/"uci.json").read_text())["language"]

    def assert_no_device_mutations(self):
        self.assertFalse(self.installed.exists())
        self.assertEqual(self.calls(),[])
        self.assertEqual(self.language(),"en")
        self.assertEqual((self.root/"etc/rc.local").read_bytes(),self.original_rc)

    def add_foreign_mount(self,target,root="/unowned/payload",dev="0:123"):
        with (self.root/"proc/self/mountinfo").open("a") as f:
            f.write(f"90 1 {dev} {root} {self.root}{target} rw - tmpfs tmpfs rw\n")

    def test_refuses_install_while_temporary_display_is_open(self):
        (self.root / "tmp/zte-vpn-screen").mkdir()
        result = self.install()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("OTHER_DEVICE_OPERATION", result.stderr)
        self.assert_no_device_mutations()

    def test_upgrade_pinned_legacy_keeps_original_backups(self):
        self.prepare_scripts()
        old = (REPO / "evidence/vpn-wifi-20260923/screen-install-before-vpn.sh").read_text()
        (self.stage / "install.sh").write_text(self.redirect(old))
        for name in ("English.ini", "Chinese.ini"):
            (self.stage / name).write_bytes((REPO / "evidence/russian-ui-compact-copy-20260922" / name).read_bytes())
        self.assert_success(self.run_script(self.stage / "install.sh", "install", self.stage, CID))
        before = {p.name:p.read_bytes() for p in (self.installed / "backup").iterdir()}
        for name in ("English.ini", "Chinese.ini"):
            (self.stage / name).write_bytes((RES / name).read_bytes())
        result = self.install()
        self.assert_success(result)
        self.assertIn("revision=20260924", result.stdout)
        self.assertEqual(before, {p.name:p.read_bytes() for p in (self.installed / "backup").iterdir()})
        self.assertIn("WiFi с VPN", (self.installed / "Chinese.ini").read_text())
        self.assertEqual(self.language(), "cn")
        self.assertFalse((self.installed / ".transaction").exists())
        self.assert_success(self.manager("disable"))
        self.assert_originals()

    def test_upgrade_vpn_caption_keeps_original_backups(self):
        self.prepare_scripts()
        previous = REPO / "evidence/vpn-profiles-screen-20260924"
        old = (previous / "screen-install-20260923.sh").read_text()
        (self.stage / "install.sh").write_text(self.redirect(old))
        for name in ("English.ini", "Chinese.ini"):
            (self.stage / name).write_bytes((previous / (name + ".20260923")).read_bytes())
        self.assert_success(self.run_script(self.stage / "install.sh", "install", self.stage, CID))
        before = {p.name:p.read_bytes() for p in (self.installed / "backup").iterdir()}
        for name in ("English.ini", "Chinese.ini"):
            (self.stage / name).write_bytes((RES / name).read_bytes())
        result = self.install()
        self.assert_success(result)
        self.assertIn("revision=20260924", result.stdout)
        self.assertIn("WiFi с VPN", (self.installed / "Chinese.ini").read_text())
        self.assertEqual(before, {p.name:p.read_bytes() for p in (self.installed / "backup").iterdir()})
        self.assert_success(self.manager("disable"))
        self.assert_originals()

    def test_install_disable_enable_preserves_stock_and_other_settings(self):
        self.assert_success(self.install())
        self.assertTrue((self.installed/".enabled").exists())
        self.assertEqual((self.root/"etc/init.d/zte_topsw_devui").stat().st_mode&0o777,0o755)
        self.assertEqual(self.language(),"cn")
        self.assertEqual((self.root/"etc/rc.local").read_bytes(),self.original_rc)
        self.assertEqual((self.root/"etc/rc.local").stat().st_mode&0o777,0o751)
        for name,target in TARGETS.items():
            self.assertEqual((self.root/target.lstrip("/")).read_bytes(),PAYLOAD[name].read_bytes())
        self.assert_success(self.manager("disable"))
        self.assertFalse((self.installed/".enabled").exists())
        self.assertEqual(self.language(),"en")
        self.assertEqual((self.root/"cache/language.txt").read_text().strip(),"english")
        self.assertEqual((self.root/"cache/language.txt").stat().st_mode&0o777,0o640)
        original_init=(REPO/"evidence/russian-ui-persistent-20260922/stock-ui-init.sh").read_text()
        self.assertEqual((self.root/"etc/init.d/zte_topsw_devui").read_text(),self.redirect(original_init))
        self.assertEqual((self.root/"etc/init.d/zte_topsw_devui").stat().st_mode&0o777,0o755)
        self.assert_originals()
        self.assertTrue((self.root/"ui-running").exists())
        self.assert_success(self.manager("enable"))
        self.assertEqual(len(json.loads((self.root/"mounts.json").read_text())),3)
        self.assertEqual(json.loads((self.root/"uci.json").read_text())["unrelated"],"preserve")

    def test_repeated_enable_disable_are_idempotent(self):
        self.assert_success(self.install())
        self.assert_success(self.manager("enable"))
        self.assert_success(self.manager("enable"))
        self.assertEqual(len(json.loads((self.root/"mounts.json").read_text())),3)
        self.assert_success(self.manager("disable"))
        self.assert_success(self.manager("disable"))
        self.assert_originals()
        self.assertFalse((self.installed/".enabled").exists())

    def test_unknown_elf_refused_before_mutation(self):
        (self.root/"usr/bin/zte_topsw_devui").write_bytes(b"unknown ELF")
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_no_device_mutations()

    def test_unknown_stock_init_refused_before_mutation(self):
        init=self.root/"etc/init.d/zte_topsw_devui"
        before=init.read_text()+"\n# unrelated user edit\n"
        init.write_text(before)
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assertEqual(init.read_text(),before)
        self.assert_no_device_mutations()

    def test_unknown_firmware_refused_before_mutation(self):
        result=self.install(MOCK_FIRMWARE_SHA="f"*64)
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_no_device_mutations()

    def test_empty_install_cid_refused_before_mutation(self):
        self.prepare_scripts()
        result=self.run_script(self.stage/"install.sh","install",self.stage,"")
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_no_device_mutations()

    def test_changed_payload_refused_before_mutation(self):
        (self.stage/"Chinese.ini").write_text("bad payload\n")
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_no_device_mutations()

    def test_target_symlink_refused_before_mutation(self):
        target=self.root/"usr/ui/language/English.ini"
        elsewhere=self.root/"elsewhere.ini"
        target.rename(elsewhere);target.symlink_to(elsewhere)
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assertEqual(elsewhere.read_bytes(),STOCK["English.ini"].read_bytes())
        self.assert_no_device_mutations()

    def test_target_parent_symlink_refused_before_mutation(self):
        target=self.root/"usr/ui/language"
        elsewhere=self.root/"elsewhere-language"
        target.rename(elsewhere);target.symlink_to(elsewhere)
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_no_device_mutations()

    def test_foreign_equal_bytes_mount_refused(self):
        self.add_foreign_mount("/usr/bin/zte_topsw_devui")
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_no_device_mutations()

    def test_foreign_ancestor_mount_refused(self):
        self.add_foreign_mount("/usr/ui")
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_no_device_mutations()

    def test_foreign_boot_hook_is_preserved(self):
        hook=self.write("/etc/init.d/zte_imei_screen_ru","#!/bin/sh\n# unrelated owner\n",0o755)
        before=hook.read_bytes()
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assertEqual(hook.read_bytes(),before)
        self.assert_no_device_mutations()

    def test_source_root_symlink_is_preserved(self):
        unrelated=self.root/"unrelated-data";unrelated.mkdir()
        (unrelated/"keep").write_text("preserve")
        self.installed.symlink_to(unrelated)
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assertTrue(self.installed.is_symlink())
        self.assertEqual((unrelated/"keep").read_text(),"preserve")
        self.assertFalse(any(x.startswith("service-") or x.startswith("mount-") for x in self.calls()))

    def test_noexec_data_refused(self):
        p=self.root/"proc/self/mountinfo"
        p.write_text(p.read_text().replace(f"{self.root}/data rw -",f"{self.root}/data rw,noexec -"))
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_no_device_mutations()

    def test_unrelated_pending_uci_refused_without_commit(self):
        p=self.root/"uci.json";state=json.loads(p.read_text())
        state["pending"]="zwrt_deviceui.Device.other_setting='pending'\n";p.write_text(json.dumps(state))
        result=self.install()
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assertEqual(json.loads(p.read_text()),state)
        self.assertFalse(any(x.startswith("uci-commit") or x.startswith("service-") for x in self.calls()))

    def test_second_mount_failure_restores_english_and_original_elf(self):
        result=self.install(MOCK_FAIL="mount-Chinese.ini")
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_originals()
        self.assertEqual(self.language(),"en")
        self.assertFalse((self.installed/".enabled").exists())
        self.assertEqual(json.loads((self.root/"mounts.json").read_text()),[])
        self.assertTrue((self.root/"ui-running").exists())

    def test_failed_candidate_start_restores_original_ui(self):
        result=self.install(MOCK_FAIL_CANDIDATE_START="1")
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assert_originals()
        self.assertEqual(self.language(),"en")
        self.assertTrue((self.root/"ui-running").exists())
        self.assertFalse((self.installed/".enabled").exists())

    def test_partial_disable_retry_keeps_recovery_marker(self):
        self.assert_success(self.install())
        result=self.manager("disable",MOCK_FAIL="umount-zte_topsw_devui")
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assertFalse((self.installed/".enabled").exists())
        self.assertTrue((self.installed/".transaction").exists())
        self.assertTrue((self.root/"ui-running").exists())
        self.assert_success(self.manager("disable"))
        self.assert_originals()
        self.assertFalse((self.installed/".transaction").exists())

    def test_cold_boot_enabled_binds_three_before_stock_ui_start(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        self.assert_success(self.boot())
        self.assertEqual(len(json.loads((self.root/"mounts.json").read_text())),3)
        self.assertEqual(self.language(),"cn")
        self.assertFalse((self.root/"ui-running").exists())
        self.assertFalse(any(x.startswith("service-") for x in self.calls()))

    def test_cold_boot_interrupted_transaction_restores_english(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        (self.installed/".enabled").unlink()
        (self.installed/".transaction").write_text("enabling\n")
        self.boot()
        self.assert_originals()
        self.assertEqual(self.language(),"en")
        self.assertEqual((self.root/"cache/language.txt").read_text().strip(),"english")
        self.assertFalse((self.installed/".enabled").exists())
        self.assertFalse(any(x.startswith("service-") for x in self.calls()))

    def test_cold_boot_changed_payload_restores_english_without_mounts(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        (self.installed/"Chinese.ini").write_text("corrupt candidate\n")
        self.boot()
        self.assert_originals()
        self.assertEqual(self.language(),"en")
        self.assertEqual(json.loads((self.root/"mounts.json").read_text()),[])
        self.assertFalse((self.installed/".enabled").exists())
        self.assertFalse(any(x.startswith("service-") for x in self.calls()))

    def test_cold_boot_new_firmware_does_not_mount_old_patch(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        self.boot(MOCK_FIRMWARE_SHA="f"*64)
        self.assert_originals()
        self.assertEqual(self.language(),"en")
        self.assertEqual(json.loads((self.root/"mounts.json").read_text()),[])
        self.assertFalse((self.installed/".enabled").exists())
        self.assertFalse(any(x.startswith("service-") for x in self.calls()))

    def test_disabled_clean_boot_preserves_later_user_chinese_choice(self):
        self.assert_success(self.install())
        self.assert_success(self.manager("disable"))
        p=self.root/"uci.json";state=json.loads(p.read_text());state["language"]="cn";p.write_text(json.dumps(state))
        (self.root/"cache/language.txt").write_text("chinese")
        self.cold_boot_state()
        self.assert_success(self.boot())
        self.assert_originals()
        self.assertEqual(self.language(),"cn")
        self.assertEqual((self.root/"cache/language.txt").read_text(),"chinese")
        self.assertFalse(any(x.startswith("uci-set") or x.startswith("service-") for x in self.calls()))

    def test_install_accepts_stock_chinese_language_and_disable_uses_english(self):
        p=self.root/"uci.json";state=json.loads(p.read_text());state["language"]="cn";p.write_text(json.dumps(state))
        (self.root/"cache/language.txt").write_text("chinese")
        self.assert_success(self.install())
        self.assertEqual((self.installed/"backup/language").read_text().strip(),"cn")
        self.assertEqual((self.installed/"backup/cache").read_text(),"chinese")
        self.assert_success(self.manager("disable"))
        self.assertEqual(self.language(),"en")
        self.assertEqual((self.root/"cache/language.txt").read_text(),"english")
        self.assert_originals()

    def test_power_loss_after_cn_before_enabled_retains_recovery_transaction(self):
        result=self.install(MOCK_CRASH="cn-without-enabled")
        self.assertEqual(result.returncode,-9,result.stdout+result.stderr)
        self.assertTrue((self.installed/".transaction").exists())
        self.assertFalse((self.installed/".enabled").exists())
        self.cold_boot_state()
        self.boot()
        self.assertEqual(self.language(),"en")
        self.assert_originals()

    def test_power_loss_after_enabled_before_transaction_cleanup_restores_safely(self):
        result=self.install(MOCK_CRASH="enabled-with-transaction")
        self.assertEqual(result.returncode,-9,result.stdout+result.stderr)
        self.assertTrue((self.installed/".transaction").exists())
        self.assertTrue((self.installed/".enabled").exists())
        self.cold_boot_state()
        self.boot()
        self.assertEqual(self.language(),"en")
        self.assert_originals()
        self.assertFalse((self.installed/".enabled").exists())

    def test_power_loss_during_failed_boot_recovery_remains_recoverable(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        (self.installed/"Chinese.ini").write_text("corrupt candidate\n")
        result=self.boot(MOCK_CRASH="enabled-with-transaction")
        self.assertEqual(result.returncode,-9,result.stdout+result.stderr)
        self.assertTrue((self.installed/".transaction").exists())
        self.cold_boot_state()
        self.boot()
        self.assertEqual(self.language(),"en")
        self.assert_originals()
        self.assertFalse((self.installed/".enabled").exists())

    def test_corrupt_manager_service_fallback_restores_english_without_execution(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        (self.installed/"manager.sh").write_text("echo CORRUPT_MANAGER_EXECUTED; exit 90\n")
        result=self.boot_service()
        self.assertNotIn("CORRUPT_MANAGER_EXECUTED",result.stdout)
        self.assertEqual(self.language(),"en")
        self.assertEqual((self.root/"cache/language.txt").read_text(),"english")
        self.assert_originals()
        self.assertFalse((self.installed/".enabled").exists())
        self.assertFalse(any(x.startswith("service-") or x.startswith("mount-") for x in self.calls()))

    def test_recovery_does_not_start_unknown_elf(self):
        self.assert_success(self.install())
        (self.root/"calls").write_text("")
        result=self.manager("disable",MOCK_CORRUPT_AFTER_UI_UNMOUNT="1")
        self.assertNotEqual(result.returncode,0,result.stdout)
        self.assertFalse((self.root/"ui-running").exists())
        self.assertTrue((self.installed/".transaction").exists())
        self.assertNotIn("service-start",self.calls())

    def test_existing_s48_dispatch_applies_localization_before_ui_start(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        self.assert_success(self.start_stock_ui())
        self.assertEqual(len(json.loads((self.root/"mounts.json").read_text())),3)
        self.assertTrue((self.root/"ui-running").exists())
        calls=self.calls()
        self.assertLess(calls.index("mount-zte_topsw_devui"),calls.index("service-start"))
        self.assertEqual(calls.count("service-start"),1)
        self.assertNotIn("service-stop",calls)

    def test_existing_s48_dispatch_starts_stock_ui_after_corrupt_payload_recovery(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        (self.installed/"Chinese.ini").write_text("corrupt candidate\n")
        self.assert_success(self.start_stock_ui())
        self.assert_originals()
        self.assertEqual(self.language(),"en")
        self.assertTrue((self.root/"ui-running").exists())
        self.assertFalse((self.installed/".enabled").exists())
        self.assertNotIn("service-stop",self.calls())

    def test_existing_s48_refuses_corrupt_boot_hook_but_starts_stock_ui(self):
        self.assert_success(self.install())
        self.cold_boot_state()
        (self.root/"etc/init.d/zte_imei_screen_ru").write_text("#!/bin/sh\necho CORRUPT_HOOK_EXECUTED\n")
        result=self.start_stock_ui()
        self.assert_success(result)
        self.assertNotIn("CORRUPT_HOOK_EXECUTED",result.stdout+result.stderr)
        self.assert_originals()
        self.assertTrue((self.root/"ui-running").exists())
        self.assertEqual(json.loads((self.root/"mounts.json").read_text()),[])


if __name__ == "__main__":
    unittest.main(verbosity=2)
