// Fixed backend codes; arbitrary diagnostic text is never displayed.
export const safeEsimErrors = new Set([
  "card_not_euicc", "card_busy", "card_open_rejected", "card_cleanup_unknown", "card_not_ready",
  "card_reset_failed", "card_power_restore_failed",
  "operation_lock_failed", "launcher_operation_refused", "radio_read_failed", "radio_not_online", "radio_set_failed", "radio_offline_failed", "radio_restore_failed", "modem_readback_failed", "modem_slot_mismatch", "modem_iccid_mismatch", "esim_busy",
  "bridge_already_open",
  "bridge_cleanup_failed",
  "bridge_missing",
  "card_changed",
  "component_already_closed",
  "component_closed",
  "component_eof",
  "component_exit_failed",
  "component_start_failed",
  "delete_confirmation_required",
  "firmware_check_failed",
  "http_destination_refused",
  "http_failed",
  "http_id_exhausted",
  "http_reply_missing",
  "http_unavailable",
  "invalid_activation_code",
  "invalid_apdu_reply",
  "invalid_arguments",
  "invalid_confirmation_code",
  "invalid_http_reply",
  "invalid_http_request",
  "invalid_json",
  "invalid_lpac_message",
  "invalid_lpac_result",
  "invalid_notifications",
  "invalid_output",
  "invalid_request",
  "invalid_snapshot",
  "job_deadline_exceeded",
  "job_message_limit",
  "job_start_failed",
  "lpac_failed",
  "lpac_result_missing",
  "message_too_large",
  "multiple_lpac_results",
  "notification_cleanup_failed",
  "postcondition_failed",
  "profile_not_disabled",
  "profile_not_found",
  "request_missing",
  "resource_cleanup_failed",
  "resource_integrity_failed",
  "resource_ownership_changed",
  "snapshot_changed",
  "snapshot_cleanup_failed",
  "snapshot_missing",
  "snapshot_required",
  "stream_read_failed",
  "stream_write_failed",
  "temporary_resource_failed",
  "unexpected_component_output",
  "unsupported_device",
  "unsupported_firmware",
  "unsupported_protocol",
  "unterminated_message"
])

// Exact helper catalog: snapshot-diagnostics/component-error-codes.json.
// Unknown fields and stderr never become diagnostics.
export const safeComponentErrors = new Set([
  "lock_unavailable",
  "lock_random_failed",
  "lock_owner_failed",
  "lock_metadata_failed",
  "lock_release_failed",
  "lock_ownership_changed",
  "lock_retained",
  "selection_read_failed",
  "selection_mismatch",
  "qmi_connect_error",
  "qmi_open_rejected",
  "qmi_open_unknown",
  "channel_open_outcome_unknown",
  "channel_close_failed",
  "card_cleanup_unknown",
  "card_not_ready",
  "unsupported_channel",
  "qmi_transmit_error",
  "short_apdu_response",
  "snapshot_response_too_large",
  "snapshot_continuation_limit",
  "snapshot_card_status_error",
  "eid_command_error",
  "eid_parse_error",
  "eid_mismatch",
  "profiles_command_error",
  "profiles_parse_error",
  "stdout_error",
  "stdin_error",
  "unterminated_json_line",
  "input_line_too_large",
  "invalid_json_line",
  "invalid_header",
  "invalid_expected_eid",
  "missing_header",
  "invalid_arguments",
  "bridge_operation_failed",
  "already_connected",
  "already_open",
  "session_failed",
  "not_connected",
  "not_open",
  "missing_owned_connection",
  "empty_read_command",
  "invalid_envelope",
  "invalid_function",
  "invalid_aid",
  "aid_not_allowed",
  "invalid_apdu",
  "invalid_hex",
  "unsupported_function"
])
export const componentError = (value: unknown): string | undefined => typeof value === 'string' && safeComponentErrors.has(value) ? value : undefined
export function failureMessage(code: string): string {
  switch (code) {
    case 'card_busy': return 'The card is busy with another operation. Wait for it to finish, then read profiles again.'
    case 'card_open_rejected': return 'The modem refused to open the card channel. Wait a moment, then read profiles again. No profile operation was retried.'
    case 'card_cleanup_unknown': return 'Card channel cleanup is unconfirmed. Restart the modem before retrying, then read profiles again. Do not remove the card lock manually.'
    case 'card_not_euicc': return 'Ordinary SIM: eSIM management is unavailable.'
    case 'card_not_ready': return 'The selected SIM application is not ready. Wait, then read profiles again. No profile operation was retried.'
    case 'card_reset_failed': return 'The SIM restart is unconfirmed. Read profiles again and check the switch result. No automatic retry was made.'
    case 'card_power_restore_failed': return 'SIM power restoration is unconfirmed. Restart the modem before trying again, then read profiles again.'
    case 'radio_restore_failed': return 'Normal radio mode was not confirmed. Check flight mode on the modem, then read profiles again. No automatic retry was attempted.'
    default: return 'The result is unconfirmed. Read profiles again before retrying; no operation is repeated automatically.'
  }
}
