#!/bin/sh
# Read capabilities or control only verified application services for this boot.
set -eu
umask 077
export PATH=/usr/sbin:/usr/bin:/sbin:/bin
fail() { printf 'ACCESS_ERROR %s\n' "$1" >&2; exit 1; }
hash() { sha256sum "$1" | awk '{print $1}'; }
plain() {
    test -f "$1" && test ! -L "$1" && test "$(stat -c %u "$1")" = 0 || return 1
    case "$(stat -c %a "$1")" in 600|644|700|755) ;; *) return 1;; esac
}
safe_dir() {
    test -d "$1" && test ! -L "$1" && test "$(stat -c %u "$1")" = 0 || return 1
    case "$(stat -c %a "$1")" in 700|750|755) ;; *) return 1;; esac
}
identity() {
    test "$(id -u)" = 0 && test "$(uname -s)" = Linux && test "$(uname -m)" = aarch64 &&
    test "$(cat /sys/block/mmcblk0/device/cid)" = "$cid"
}
# Only PIDs that own a LISTEN socket at the selected port. No name-based kill.
listeners() {
    inodes=$(awk -v port="$1" '$2 ~ (":" port "$") && $4=="0A" {print $10}' /proc/net/tcp /proc/net/tcp6 | sort -u)
    test -n "$inodes" || return 0
    for process in /proc/[0-9]*; do
        test -d "$process/fd" || continue
        matched=0
        for fd in "$process"/fd/*; do
            link=$(readlink "$fd" 2>/dev/null || true)
            for inode in $inodes; do if test "$link" = "socket:[$inode]"; then matched=1; break; fi; done
            test "$matched" = 0 || break
        done
        test "$matched" = 0 || printf '%s\n' "${process#/proc/}"
    done
}
port_open() { awk -v port="$1" '$2 ~ (":" port "$") && $4=="0A" {found=1} END{exit !found}' /proc/net/tcp /proc/net/tcp6; }
# Generated from BundledAgent's independently verified release registry.
# BEGIN_REVIEWED_AGENT_HASHES
known_agent_hash() {
    case "$1" in
      0563f12c64311bf1058cd3a4136a0b328d07e1cba7b8e92b962ec5bf3c7e4215|07154bffefb022eff87c46deb51b73501110edd6e6bf9248ccbec248b2fbe56e|076824a90eec46702744ae0f383872841d3c4704216ae32de4725f906f86a550|3da0915669ca101fe8b2faef3d683405957a2fbd49000a58257d28868321b3df|413ba4b0a07540d6901e87e74c9730196eb3373cf35b8914e31a8194bfe5a839|43ecb851c163a0575cdcb0e21561ae5097bb52026daac33cb46c85deba6a278d|4d28622aa277c5407b142dea7f3c919c992b8beda9ec622a889a02bd7ab721eb|52324f0c99f13a3445c08431f8b4ed15b468352f5b20709e3304cf4d32577b48|5deb5e93ee7d37403b0a931f0e127c64e4d9b4825855653e5b890572b02848aa|6168ae6c539bb3ca7136eb40a1d4cae03d75aa18900be105f2ff2d5016da4b5c|66c3fb83f3db5b194a39db563a453d421f6a4f3ccb9228cf360883ce2fed1629|7a2d1a517d564a3d66dfe98e6622be6ca2428635aa9cbd83cbf02c179dd7703e|7cdddfbf529a0de70726cafbfacbd56d77286b001feb1efcf123ef323b07d433|8d72032d37fff80195a106b257cc1f72ec76a4085224b0161a4bc81cd0167a4e|8ee8073b684613f358a5b857f7ed85ac165fc96f0d74980b04be006659ebea67|9def1ae625eeee2d3357c5583b441c3a910ef546513d10c80355536b3b5146e7|b082c8dfc8238d73dc0bdee7453cd60e0816f7f16b2febbf42d16ac7b6bfd466|b23d57c223e898df9d26574fdfbd01a0b6f4d3835ebe9752ed642b0484625ef7|b5c27d398e85db8a87d454d729cb36f22e54a2d832fb1117b27aa055e5032537|be945c0a7181070aa69be3bb579a1e967a1cf147b2af2987f31ae5d242b10a66|c50ba6b7ac6f77c581c2b657ba769f976d8d20aca0c6b7d08c9254ef2de9d346|c7fd7f594db16c71f67ba066d112fefabca4290f74cc3f2506350260479a19f6|d3fd8a8316eb1f63d6e737ef99f8cf7e3a2946cf80acb8df6c3d8bd16911bce4|e138c8eca5612c02e8b40e2af53eb6bfb65f138b0992f2f5dca4a02cc4cac762|e9f3e2170a7a2fa80a4836fd7d0db92c4aa119b4b8cceaa0907450123de29d19|ec4c21f70c666d28b016445eb9ab391e05d21b0974d3c6553671aa73acd183da|f2e0404c2c1be4c058c27b0a19c99c1d380e1c91d61503661424d53e799e235b|f85bd358b6d2b8d418375d45b52472f13e5a25942ed670d6671c275c33204d68) return 0;;
      *) return 1;;
    esac
}
# END_REVIEWED_AGENT_HASHES
agent_launcher_valid() {
    plain "$1" && test "$(stat -c %h "$1")" = 1 || return 1
    case "$(stat -c %a "$1")" in 600|700) ;; *) return 1;; esac
    size=$(stat -c %s "$1") || return 1
    test "$size" -gt 0 && test "$size" -le 16384 || return 1
    test "$(LC_ALL=C tr -d '\000' < "$1" | wc -c)" -eq "$size" || return 1
    # Accept current startup plus the exact formats generated by earlier releases.
    # The password is parsed as literal shell-quoted data, never evaluated.
    LC_ALL=C awk '
      function reject() {bad=1;exit 1}
      function quoted(value, i,q,bs) {
        q=sprintf("%c",39);bs=sprintf("%c",92)
        if(length(value)<3 || substr(value,1,1)!=q || substr(value,length(value),1)!=q)return 0
        for(i=2;i<length(value);i++)if(substr(value,i,1)==q) {
          if(substr(value,i,4)!=q bs q q || i+3>=length(value))return 0;i+=3
        }
        return 1
      }
      function bind_valid(line, prefix,value,ip,a,n,i) {
        prefix="export ZTE_AGENT_BIND=";if(index(line,prefix)!=1)return 0
        value=substr(line,length(prefix)+1);if(!quoted(value))return 0
        ip=substr(value,2,length(value)-2);if(ip !~ /:9090$/)return 0
        sub(/:9090$/,"",ip);n=split(ip,a,".");if(n!=4)return 0
        for(i=1;i<=4;i++)if(a[i] !~ /^[0-9]+$/ || (length(a[i])>1 && substr(a[i],1,1)=="0") || a[i]+0>255)return 0
        return 1
      }
      /\r/ {reject()}
      /^[ \t]*$/ || /^#/ {next}
      /[[:cntrl:]]/ {reject()}
      {lines[++n]=$0;if(n>8)reject()}
      END {
        if(bad || (n!=4 && n!=5 && n!=6 && n!=8))exit 1
        prefix="export ZTE_AGENT_PASSWORD="
        if(index(lines[1],prefix)!=1 || !quoted(substr(lines[1],length(prefix)+1)))exit 1
        next_line=2
        if(lines[next_line]=="unset ZTE_AGENT_MODE" && lines[next_line+1]=="unset ZTE_AGENT_BIND")next_line+=2
        q=sprintf("%c",39)
        if(lines[next_line]=="export ZTE_AGENT_MODE=" q "discovery" q) {
          if(!bind_valid(lines[next_line+1]))exit 1
          next_line+=2
        } else if(bind_valid(lines[next_line]))next_line++
        if(n!=next_line+2 || lines[next_line]!="unset ZTE_AGENT_PIN" || lines[next_line+1]!="trap " sprintf("%c%c",39,39) " HUP")exit 1
        if(lines[next_line+2]!="nohup sh -c " q "/data/zte-agent 2>&1 | logger -t zte-agent" q " >/dev/null 2>&1 </dev/null &")exit 1
      }' "$1"
}
dashboard_root() {
    # Validate the selected document root before granting controls or stopping a
    # running listener. The installed release uses www.current, not /data/www.
    docroot=/data/www
    if test -e /data/www.current || test -L /data/www.current; then
        test -L /data/www.current || return 1
        docroot=$(readlink -f /data/www.current) || return 1
    fi
    case "$docroot" in
      /data/www) ;;
      /data/open-u60-dashboards/*) safe_dir /data/open-u60-dashboards || return 1;;
      /data/open-u60-agent-releases/2.4.1-ru-ttl.1/dashboard)
        safe_dir /data/open-u60-agent-releases && safe_dir /data/open-u60-agent-releases/2.4.1-ru-ttl.1 || return 1;;
      *) return 1;;
    esac
    safe_dir "$docroot" && plain "$docroot/index.html"
}
service_info() {
    service=$1; controlled=0; exe=; port=; launch=
    case "$service" in
      stockWeb) port=0050;;
      dashboard)
        port=1F90; exe=/data/bin/dashboard-uhttpd; launch=/data/local/tmp/start_dashboard.sh
        if safe_dir /data && safe_dir /data/bin && plain "$exe" && test "$(hash "$exe")" = 76f021c43a02eab5bb634b01461370fcb8bfb270b1f14e348e5b57acb43b1d12 &&
           plain "$launch" && test "$(hash "$launch")" = 2f4c2b45dd6142fcc5b6b7aeaf5c0fc5923ba647f4cb3b95fe45e6b1f665c301 &&
           plain /data/local/tmp/stop_open_u60_listener.sh && test "$(hash /data/local/tmp/stop_open_u60_listener.sh)" = 82474a9f2ee061d105041986efb904c2cb0ee43353a7be94cd2ad18f450d9d08 && dashboard_root; then controlled=1; fi;;
      agent)
        port=2382; exe=/data/zte-agent; launch=/data/zte-imei-studio/start_zte_agent.sh
        if safe_dir /data && safe_dir /data/zte-imei-studio && test "$(stat -c %a /data/zte-imei-studio)" = 700 && plain "$exe" && test -x "$exe" && known_agent_hash "$(hash "$exe")" && agent_launcher_valid "$launch"; then controlled=1; fi;;
      managementSSH) port=08AE;;
      userSSH)
        port=08AF; exe=/data/zte-imei-admin/bin/dropbear; launch=/data/zte-imei-admin/start-ssh-users.sh
        if safe_dir /data && safe_dir /data/zte-imei-admin && safe_dir /data/zte-imei-admin/bin && safe_dir /etc/zte-imei-admin && plain "$exe" && test "$(hash "$exe")" = e3833acdaa8b11e6150f82a35d3dc53d685561d5504ef337ad4af5e530345378 &&
           plain "$launch" && test "$(hash "$launch")" = 35d0e51c65f0ba3499c62d16df1447b91c67e4e0cca26bc9c0e05efb712ef297 &&
           plain /etc/zte-imei-admin/listen-address && test "$(cat /etc/zte-imei-admin/listen-address)" = "$address"; then controlled=1; fi;;
      adb) ;; *) return 1;;
    esac
}
owned_pids() {
    pids=$(listeners "$port")
    if port_open "$port" && test -z "$pids"; then return 1; fi
    count=0
    for pid in $pids; do
        count=$((count+1)); test "$count" = 1 || return 1
        test "$(readlink "/proc/$pid/exe" 2>/dev/null || true)" = "$exe" || return 1
        if test "$service" = userSSH; then
            tr '\000' '\n' < "/proc/$pid/cmdline" | grep -qFx "$address:2223" &&
            tr '\000' '\n' < "/proc/$pid/cmdline" | grep -qFx -- -w &&
            tr '\000' '\n' < "/proc/$pid/cmdline" | awk 'prev=="-G" && $0=="zteimei" {yes=1} {prev=$0} END{exit !yes}' || return 1
        fi
    done
}
report() {
    printf 'ACCESS_SCHEMA 1\n'
    for item in stockWeb dashboard agent managementSSH userSSH adb; do
        service_info "$item" || return 1
        state=stopped; capability=readonly
        if test "$item" = adb; then
            state=unavailable
            for process in /proc/[0-9]*; do
                case "$(readlink "$process/exe" 2>/dev/null || true)" in /sbin/adbd|/usr/bin/adbd|/usr/sbin/adbd|/system/bin/adbd) state=running;; esac
            done
        else
            if port_open "$port"; then state=running
            elif test -n "$exe" && ! test -f "$exe"; then state=unavailable; fi
            if test "$controlled" = 1; then
                if owned_pids; then capability=control; else state=unknown; fi
            fi
        fi
        test "$item" != managementSSH || capability=protected
        printf 'ACCESS_SERVICE %s %s %s\n' "$item" "$state" "$capability"
    done
}
mode=${1:-}; cid=${2:-}; address=${3:-}
printf '%s\n' "$cid" | grep -Eq '^[a-f0-9]{32}$' || fail CID_FORMAT
printf '%s\n' "$address" | awk -F. 'NF==4 {for(i=1;i<=4;i++)if($i!~/^[0-9]+$/||$i>255)exit 1;exit 0}{exit 1}' || fail ADDRESS
identity || fail IDENTITY
case "$mode" in status) test "$#" = 3 || fail ARGUMENTS; report; exit 0;; action) test "$#" = 7 || fail ARGUMENTS;; *) fail ARGUMENTS;; esac
chosen=$4; action=$5; stage=$6; lock_token=$7
case "$chosen" in agent|dashboard|userSSH) ;; *) fail PROTECTED_SERVICE;; esac
case "$action" in start|stop|restart) ;; *) fail ACTION;; esac
case "$stage" in /tmp/zte-access-*) ;; *) fail STAGE;; esac
stage_token=${stage#/tmp/zte-access-}
test "${#stage_token}" = 36 && case "$stage_token" in *[!a-f0-9-]*) false;; *) true;; esac || fail STAGE_TOKEN
test "${#lock_token}" = 36 && case "$lock_token" in *[!a-f0-9-]*) false;; *) true;; esac || fail LOCK_TOKEN
safe_dir "$stage" && test "$(stat -c %a "$stage")" = 700 || fail STAGE_MODE
safe_dir /tmp/zte-imei-app.lock && plain /tmp/zte-imei-app.lock/owner && test "$(cat /tmp/zte-imei-app.lock/owner)" = "$lock_token" || fail GLOBAL_LOCK
# The calling SSH transport must remain on the protected application endpoint.
port_open 08AE || fail MANAGEMENT_CHANNEL
for pending in /data/zte-imei-admin/active /data/zte-imei-studio/installations/active /data/local/tmp/zte-imei-installations/active /data/local/tmp/open-u60-transactions/active /tmp/fota_install_processing; do test ! -e "$pending" && test ! -L "$pending" || fail OTHER_TRANSACTION; done
service_info "$chosen" && test "$controlled" = 1 && owned_pids || fail UNVERIFIED_SERVICE
was_running=0; test -z "$pids" || was_running=1
# Copy the validated launcher into the private stage and validate the copy too.
cp "$launch" "$stage/launcher.private.sh"
if test "$chosen" = agent; then agent_launcher_valid "$stage/launcher.private.sh" || fail LAUNCHER_CHANGED
elif test "$chosen" = dashboard; then test "$(hash "$stage/launcher.private.sh")" = 2f4c2b45dd6142fcc5b6b7aeaf5c0fc5923ba647f4cb3b95fe45e6b1f665c301 || fail LAUNCHER_CHANGED
else test "$(hash "$stage/launcher.private.sh")" = 35d0e51c65f0ba3499c62d16df1447b91c67e4e0cca26bc9c0e05efb712ef297 || fail LAUNCHER_CHANGED; fi
cleanup() { rm -f "$stage/launcher.private.sh"; }
trap cleanup EXIT
trap 'exit 130' HUP INT TERM
if test "$action" != start && test "$was_running" = 1; then
    identity && service_info "$chosen" && test "$controlled" = 1 && owned_pids && test -n "$pids" || fail SERVICE_CHANGED
    for pid in $pids; do kill -TERM "$pid" || fail STOP; done
    attempts=0
    while port_open "$port"; do attempts=$((attempts+1)); test "$attempts" -le 8 || fail STOP_TIMEOUT; sleep 1; done
fi
if test "$action" != stop; then
    # Never run a launcher if a foreign process took the port during the stop.
    service_info "$chosen" && test "$controlled" = 1 && owned_pids || fail SERVICE_CHANGED
    if test -z "$pids"; then
        identity || fail IDENTITY_CHANGED
        if test "$chosen" = dashboard; then
            dashboard_root || fail DOCROOT
            nohup "$exe" -f -h "$docroot" -p 0.0.0.0:8080 -D >/dev/null 2>&1 </dev/null &
        else sh "$stage/launcher.private.sh" >/dev/null 2>&1 || fail START; fi
        attempts=0
        until port_open "$port"; do attempts=$((attempts+1)); test "$attempts" -le 10 || fail START_TIMEOUT; sleep 1; done
    fi
    service_info "$chosen" && owned_pids && test -n "$pids" || fail START_VERIFY
    stable=$pids; sleep 1; owned_pids && test "$pids" = "$stable" || fail UNSTABLE_SERVICE
fi
report
