port=0
interface=br-vpn
except-interface=lo
bind-dynamic
dhcp-range=192.168.50.20,192.168.50.200,255.255.255.0,1h
dhcp-option=3,192.168.50.1
dhcp-option=6,192.168.50.1
dhcp-authoritative
dhcp-leasefile=/data/zte-vpn/dhcp.leases
pid-file=/tmp/zte-vpn-dnsmasq.pid
log-facility=-
